# packages in environment at /home/yellowflash/anaconda3/envs/ceuta_analysis:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
async-generator           1.10                     pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
blas                      1.0                    openblas  
bottleneck                1.3.5            py39h7deecbd_0  
brotlipy                  0.7.0           py39h27cfd23_1003  
bs4                       4.11.1               hd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h74dc2b5_0  
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.0.4            py39h06a4308_0    anaconda
cryptography              38.0.4           py39h9ce1e76_0  
dataclasses               0.8                pyh6d0b6a4_7    anaconda
datasets                  2.8.0                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
dnspython                 1.16.0                   pypi_0    pypi
emoji                     1.7.0                    pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
fftw                      3.3.9                h27cfd23_1  
filelock                  3.9.0                    pypi_0    pypi
flask                     2.1.3            py39h06a4308_0    anaconda
flask-pymongo             2.3.0              pyhd8ed1ab_0    conda-forge
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2022.11.0                pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
huggingface-hub           0.11.1                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39h06a4308_0    anaconda
itsdangerous              2.0.1              pyhd3eb1b0_0    anaconda
jinja2                    3.0.3              pyhd3eb1b0_0    anaconda
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
markupsafe                2.1.1            py39h7f8727e_0    anaconda
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
numexpr                   2.8.4            py39hd2a5715_0  
numpy                     1.23.5           py39hf838250_0  
numpy-base                1.23.5           py39h1e6e340_0  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
openssl                   1.1.1s               h0b41bf4_1    conda-forge
outcome                   1.2.0                    pypi_0    pypi
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2            py39h2ad29b5_2    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
pyarrow                   10.0.1                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pymongo                   3.12.0           py39h295c915_0    anaconda
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pysentimiento             0.5.2                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.13               haa1d7c7_2  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
responses                 0.18.0                   pypi_0    pypi
scikit-learn              1.2.0            py39h6a678d5_0  
scipy                     1.9.3            py39h32ae08f_0  
selenium                  4.7.2                    pypi_0    pypi
setuptools                66.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.40.1               h5082296_0  
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.2                   pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
transformers              4.25.1                   pypi_0    pypi
trio                      0.22.0                   pypi_0    pypi
trio-websocket            0.9.2                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.3              pyhd3eb1b0_0    anaconda
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
wsproto                   1.2.0                    pypi_0    pypi
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.8.0            py39h06a4308_0    anaconda
zlib                      1.2.13               h5eee18b_0  
